apiVersion: 1

datasources:
  - name: AllskyDB
    type: postgres
    url: db:5432
    user: allsky
    secureJsonData:
      password: allsky
    database: cloud_analysis
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
